'use client';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/header";
import GlobalContext from '../context/GlobalContext';
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [open, setOpen] = useState(false);
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContext.Provider value={{ open: open, setOpen: setOpen }}>
          <Header />
          {children}
        </GlobalContext.Provider>
      </body>
    </html>
  );
}
